language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
install:
     - dotnet tool install --global dotnet-sonarscanner
before_script:
  - export PATH="$PATH:$HOME/.dotnet/tools"

script:
    - dotnet sonarscanner begin /k:"ufukaytas_DotNet-Core-CI-Sample" /n:"ufukaytas_DotNet-Core-CI-Sample" /v:"1.0.0" /o:"ufukaytas-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="e78c314cb30918c69a6e18b2db032d622dc537fc" /d:sonar.language="cs" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.cs.opencover.reportsPaths="lcov.opencover.xml" || true
    - dotnet restore
    - dotnet build
      - dotnet sonarscanner end /d:sonar.login="e78c314cb30918c69a6e18b2db032d622dc537fc" || true
cache:
  directories:
    - '$HOME/.nuget/packages'
    - '$HOME/.local/share/NuGet/Cache'
    - '$HOME/.sonar/cache'
